/// Flutter icons EventuauIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
///
/// 
///
import 'package:flutter/widgets.dart';

class EventuauIcons {
  EventuauIcons._();

  static const _kFontFam = 'EventuauIcons';
  static const String _kFontPkg = null;

  static const IconData garcom_logo = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clown = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData buffet = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grill = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData security_man = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bartender = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tourist = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}


class EventuauIcons2 {
  EventuauIcons2._();

  static const _kFontFam = 'EventuauIcons2';
  static const String _kFontPkg = null;

  static const IconData cancel = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData handshake = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}